### ISSUE TITLE
Pass in mapping via CLI

### ISSUE THREAD

**Issue by leojhartiv** [mikew/xarcade-xinput#16] opened 2021-01-13 17:55 UTC
Love this project that you've created.  Thank you!  I'm using it with my ultimarc ipac-enabled retroarcade to launch windows games that require controllers.  

For me to really adopt this fully, I'd want to be able to pass a mapping name when executing "XArcade XInput.exe".  I have some games that don't follow the same rules around controller mappings, so this would be a great feature.

**Comment by mikew** [comment] 2021-01-14 20:26
closing as this was a duplicate of https://github.com/mikew/xarcade-xinput/issues/15

**Closed** 2021-01-14 20:26 UTC
Labels: duplicate, enhancement
